### ISSUE TITLE
Multi dimensional commands which rely on a single display associated with data fail when data item has multiple displays

### ISSUE THREAD

**Issue by cmeyer** [nion-software/experimental#35]
Take a sequence. Measure shifts. Create an additional display of the shifts (Display > Duplicate Display Item). Now use measure shifts using the sequence and the shifts. Fails!

Workaround is to remove 2nd display, but that can be difficult to find in the project.

```
Traceback (most recent call last):
  File "C:\NionApps\Developer\main\nionui\nion\ui\UserInterface.py", line 3082, in trigger
    self.on_triggered()
  File "C:\NionApps\Developer\main\nionswift\nion\swift\Facade.py", line 3277, in <lambda>
    menu.add_menu_item(menu_item_handler.menu_item_name, lambda: menu_item_handler.menu_item_execute(facade_document_controller), key_sequence=key_sequence)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NionApps\Developer\main\nionswift-experimental\nionswift_plugin\nion_experimental_tools\MultiDimensionalProcessing.py", line 462, in menu_item_execute
    assert display_item is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by cmeyer** [comment]
Would it be possible to add some heuristic method of figuring out the right display? Maybe sorting by modification date would work and using the earliest display?

**Comment by Brow71189** [comment]
Actually the user selects display items initially, which we then resolve to data items and later try to find the display item for one of the data items again.
I would say the correct solution is to use the initially selected display item directly, this way we just do what the user intended.
